[package]
name = "simple-lock"
version = "0.1.0"
edition = "2021"

[dependencies]
ckb-std = "0.17.0"
ckb-hash = {version = "0.202.0", default-features = false, features = ["ckb-contract"] }

[features]
library = []
native-simulator = ["library", "ckb-std/native-simulator"]
